### ISSUE TITLE
Error with Ruby 2.5 (default o Ubuntu Bionic)

### ISSUE THREAD

**Issue by rvalyi** [akretion/shopinvader-template#2]
Wagon needs to be updated in Gemfile.lock to achieve Ruby 2.5 compatibility.
It will also likely fix the 3 vulnerabilities found by Github in our Gemfile.lock (see https://github.com/akretion/shopinvader-deploy/network/dependencies )

From what I see, we will need to upgrade faraday in https://github.com/akretion/locomotive_shopinvader/blob/master/shop_invader.gemspec#L33
to faraday 0.14, the same version used by locomotive_coal

```
rvalyi@rvalyi-laptop:~/DEV/shopinvader-template$ bundle exec wagon deploy production -v

Pushing Site
 [failed]
    undefined method `name' for module `Kernel'

# Error description:
undefined method `name' for module `Kernel'

# Backtrace:

	/home/rvalyi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/delegate.rb:85:in `instance_method'
	/home/rvalyi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/delegate.rb:85:in `method_missing'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_site_command.rb:34:in `label_for'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:33:in `block in _push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/gems/activesupport-4.2.10/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:50:in `instrument'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_command.rb:55:in `block in _push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_command.rb:84:in `block in each_resource'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_command.rb:77:in `each'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_command.rb:77:in `each_resource'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_command.rb:54:in `_push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_command.rb:41:in `push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon.rb:73:in `push'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/lib/locomotive/wagon/cli.rb:318:in `deploy'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bundler/gems/wagon-7c59d3125d97/bin/wagon:12:in `<top (required)>'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bin/wagon:23:in `load'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bin/wagon:23:in `<main>'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
	/home/rvalyi/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
rvalyi@rvalyi-laptop:~/DEV/shopinvader-template$ rvm install ruby-2.4.4
```

**Comment by rvalyi** [comment]
cc @sbidoul Ruby 2.5 compat may interest you I think

**Comment by rvalyi** [comment]
sorry I don't remember what was the cause of this bug, but I believe it no longer shows at my end, so closing it for now at least.
